name: academic_rag_env
channels:
  - conda-forge # Add conda-forge as many of these packages are there
  - defaults
dependencies:
  - python=3.10 # Set a specific Python version that works with streamlit
  - pip
  # Conda-preferred packages (if available on conda-forge)
  - numpy==1.24.3 # example if it was in requirements.txt
  - pandas==2.1.4 # example if it was in requirements.txt
  - pytorch # often good to get from conda-forge
  - transformers==4.36.0 # also often on conda-forge
  - accelerate==0.25.0 # also often on conda-forge
  - pip:
      # All packages from your requirements.txt should go here
      # You might want to copy directly from your requirements.txt
      - accelerate==0.25.0
      - chromadb==0.4.18
      - langchain==0.1.0
      - python-dotenv==1.0.0
      - sentence-transformers==2.2.2
      - tiktoken==0.5.2
      - torch==2.1.0
      - transformers==4.36.0
      - streamlit==1.29.0
      - pypdf2==3.0.1
      - pandas==2.1.4
      - numpy==1.24.3
